<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>H.Ipc.Core</RootNamespace>
    <NoWarn>$(NoWarn);CA1819;CA2227</NoWarn>
  </PropertyGroup>

  <PropertyGroup Label="NuGet">
    <Description>Core library for Inter-Process Communication.</Description>
    <PackageTags>ipc, generator, source generator, csharp 9</PackageTags>
  </PropertyGroup>

  <ItemGroup Label="Usings">
    <Using Include="System.Diagnostics" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\H.Ipc.Generator\H.Ipc.Generator.csproj" ReferenceOutputAssembly="false" PackAsAnalyzer="true" />
    <PackageReference Include="H.Generators.Extensions" Version="1.24.2" PrivateAssets="all" IncludeInPackage="true" />
    <PackageReference Include="MessagePack" Version="3.1.4" />
    <PackageReference Include="H.Pipes.AccessControl" Version="15.0.0" />
    <None Include="..\H.Ipc.Generator\bin\$(Configuration)\net10.0\H.Generators.Extensions.dll" Pack="true" PackagePath="analyzers/dotnet" Visible="false" />
  </ItemGroup>
  
</Project>
